// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFyIfbXhmq8F-QzK5mmv0Uo1vAO80-q_Y',
    appId: '1:974852336066:web:0fbea1b79510e0f2bb4e5b',
    messagingSenderId: '974852336066',
    projectId: 'student-grade-app-67022511022',
    authDomain: 'student-grade-app-67022511022.firebaseapp.com',
    storageBucket: 'student-grade-app-67022511022.firebasestorage.app',
    measurementId: 'G-SLX3DTV091',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN3Ip_PZZI7IG8l9jXzeTUU9yuJis_Ayg',
    appId: '1:974852336066:android:e235403f5d4f217cbb4e5b',
    messagingSenderId: '974852336066',
    projectId: 'student-grade-app-67022511022',
    storageBucket: 'student-grade-app-67022511022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVfXI90H8IBAo7dLIhWjfAdel8rLx63A',
    appId: '1:974852336066:ios:82ae9b46b04eb55fbb4e5b',
    messagingSenderId: '974852336066',
    projectId: 'student-grade-app-67022511022',
    storageBucket: 'student-grade-app-67022511022.firebasestorage.app',
    iosBundleId: 'com.example.studentGradeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVfXI90H8IBAo7dLIhWjfAdel8rLx63A',
    appId: '1:974852336066:ios:82ae9b46b04eb55fbb4e5b',
    messagingSenderId: '974852336066',
    projectId: 'student-grade-app-67022511022',
    storageBucket: 'student-grade-app-67022511022.firebasestorage.app',
    iosBundleId: 'com.example.studentGradeApp',
  );
}
